# Generated by Django 4.2.5 on 2023-10-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposexames',
            name='tipo',
            field=models.CharField(choices=[('I', 'Exame de imagem'), ('S', 'Exame de sangue')], max_length=2),
        ),
    ]
